-- ============================================================
-- 000_reconcile_schema.sql — PHASE 0: SEMA UZLASTIRMA (OTOMATIK)
-- Eski/yarim DB'lerde index'lerin ihtiyac duydugu TUM kolonlari
-- onceden garanti eder. ALTER IF EXISTS + ADD COLUMN IF NOT EXISTS.
-- Bu blok her seyden ONCE calisir; tum "column X does not exist"
-- hatalarini engeller.
-- ============================================================

ALTER TABLE IF EXISTS public.activity_logs ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.activity_logs ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE IF EXISTS public.ai_suggestions_cache ADD COLUMN IF NOT EXISTS expires_at timestamptz;
ALTER TABLE IF EXISTS public.ai_suggestions_cache ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.battery_logs ADD COLUMN IF NOT EXISTS member_id uuid;
ALTER TABLE IF EXISTS public.battery_logs ADD COLUMN IF NOT EXISTS timestamp timestamptz;
ALTER TABLE IF EXISTS public.budget_entries ADD COLUMN IF NOT EXISTS date timestamptz;
ALTER TABLE IF EXISTS public.budget_entries ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.call_sessions ADD COLUMN IF NOT EXISTS callee_id uuid;
ALTER TABLE IF EXISTS public.call_sessions ADD COLUMN IF NOT EXISTS caller_id uuid;
ALTER TABLE IF EXISTS public.call_sessions ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.call_sessions ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE IF EXISTS public.call_signaling ADD COLUMN IF NOT EXISTS session_id uuid;
ALTER TABLE IF EXISTS public.child_accounts ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.child_accounts ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE IF EXISTS public.child_activity_logs ADD COLUMN IF NOT EXISTS child_id uuid;
ALTER TABLE IF EXISTS public.child_activity_logs ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.child_development_logs ADD COLUMN IF NOT EXISTS child_id uuid;
ALTER TABLE IF EXISTS public.child_development_logs ADD COLUMN IF NOT EXISTS log_type text;
ALTER TABLE IF EXISTS public.child_development_logs ADD COLUMN IF NOT EXISTS logged_at timestamptz;
ALTER TABLE IF EXISTS public.child_homeworks ADD COLUMN IF NOT EXISTS child_id uuid;
ALTER TABLE IF EXISTS public.child_homeworks ADD COLUMN IF NOT EXISTS due_date timestamptz;
ALTER TABLE IF EXISTS public.child_homeworks ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.child_homeworks ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE IF EXISTS public.child_schedules ADD COLUMN IF NOT EXISTS child_id uuid;
ALTER TABLE IF EXISTS public.child_schedules ADD COLUMN IF NOT EXISTS day_of_week int;
ALTER TABLE IF EXISTS public.child_sessions ADD COLUMN IF NOT EXISTS child_id uuid;
ALTER TABLE IF EXISTS public.child_sessions ADD COLUMN IF NOT EXISTS token text;
ALTER TABLE IF EXISTS public.context_snapshots ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.context_snapshots ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.context_snapshots ADD COLUMN IF NOT EXISTS member_id uuid;
ALTER TABLE IF EXISTS public.crash_events ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.crash_events ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.crash_events ADD COLUMN IF NOT EXISTS is_false_positive boolean;
ALTER TABLE IF EXISTS public.crash_events ADD COLUMN IF NOT EXISTS member_id uuid;
ALTER TABLE IF EXISTS public.crash_events ADD COLUMN IF NOT EXISTS response_status text;
ALTER TABLE IF EXISTS public.crash_events ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE IF EXISTS public.emergency_actions ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.emergency_actions ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.emergency_actions ADD COLUMN IF NOT EXISTS status_state text;
ALTER TABLE IF EXISTS public.emergency_contacts ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.error_logs ADD COLUMN IF NOT EXISTS timestamp timestamptz;
ALTER TABLE IF EXISTS public.error_logs ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE IF EXISTS public.events ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.events ADD COLUMN IF NOT EXISTS start_time timestamptz;
ALTER TABLE IF EXISTS public.events ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE IF EXISTS public.family_backups ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.family_backups ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.family_contacts ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.family_documents ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.family_documents ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.family_history ADD COLUMN IF NOT EXISTS event_date timestamptz;
ALTER TABLE IF EXISTS public.family_history ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.family_media ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.family_media ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.family_members ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.family_moods ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.family_moods ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.geolocations ADD COLUMN IF NOT EXISTS child_id uuid;
ALTER TABLE IF EXISTS public.geolocations ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.geolocations ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE IF EXISTS public.health_cards ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.health_cards ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE IF EXISTS public.household_tasks ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE IF EXISTS public.hub_widgets ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.hub_widgets ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE IF EXISTS public.location_history ADD COLUMN IF NOT EXISTS batch_id uuid;
ALTER TABLE IF EXISTS public.location_history ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.location_history ADD COLUMN IF NOT EXISTS member_id uuid;
ALTER TABLE IF EXISTS public.location_history ADD COLUMN IF NOT EXISTS recorded_at timestamptz;
ALTER TABLE IF EXISTS public.messages ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.messages ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.mood_entries ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.mood_entries ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.mood_entries ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE IF EXISTS public.profiles ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE IF EXISTS public.profiles ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.reminder_interactions ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.reminder_interactions ADD COLUMN IF NOT EXISTS member_id uuid;
ALTER TABLE IF EXISTS public.reminder_interactions ADD COLUMN IF NOT EXISTS reminder_id uuid;
ALTER TABLE IF EXISTS public.routine_history ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.routine_history ADD COLUMN IF NOT EXISTS routine_id uuid;
ALTER TABLE IF EXISTS public.routine_suggestions ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.routines ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.routines ADD COLUMN IF NOT EXISTS type text;
ALTER TABLE IF EXISTS public.safe_arrivals ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.safe_arrivals ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.safe_arrivals ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE IF EXISTS public.safe_zones ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.security_logs ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.security_logs ADD COLUMN IF NOT EXISTS event_type text;
ALTER TABLE IF EXISTS public.security_logs ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE IF EXISTS public.sensor_logs ADD COLUMN IF NOT EXISTS member_id uuid;
ALTER TABLE IF EXISTS public.sensor_logs ADD COLUMN IF NOT EXISTS timestamp timestamptz;
ALTER TABLE IF EXISTS public.settings ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE IF EXISTS public.shopping_items ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.shopping_items ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.shopping_items ADD COLUMN IF NOT EXISTS is_completed boolean;
ALTER TABLE IF EXISTS public.smart_reminders ADD COLUMN IF NOT EXISTS created_by text;
ALTER TABLE IF EXISTS public.smart_reminders ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.sos_alerts ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.sos_alerts ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.sos_alerts ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE IF EXISTS public.support_sessions ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE IF EXISTS public.support_sessions ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE IF EXISTS public.task_schedules ADD COLUMN IF NOT EXISTS assigned_to text;
ALTER TABLE IF EXISTS public.task_schedules ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.tasks ADD COLUMN IF NOT EXISTS assigned_to text;
ALTER TABLE IF EXISTS public.tasks ADD COLUMN IF NOT EXISTS family_id uuid;
ALTER TABLE IF EXISTS public.tasks ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE IF EXISTS public.tracking_analytics ADD COLUMN IF NOT EXISTS date timestamptz;
ALTER TABLE IF EXISTS public.tracking_analytics ADD COLUMN IF NOT EXISTS member_id uuid;
ALTER TABLE IF EXISTS public.weather_cache ADD COLUMN IF NOT EXISTS family_id uuid;

-- Ekstra kolonlar (index disi ama policy/view kullaniyor)
ALTER TABLE IF EXISTS public.mood_entries ADD COLUMN IF NOT EXISTS mood  text;
ALTER TABLE IF EXISTS public.mood_entries ADD COLUMN IF NOT EXISTS emoji text;
ALTER TABLE IF EXISTS public.safe_zones     ADD COLUMN IF NOT EXISTS type text DEFAULT 'custom';
ALTER TABLE IF EXISTS public.family_history ADD COLUMN IF NOT EXISTS type text DEFAULT 'memory';
ALTER TABLE IF EXISTS public.subscriptions ADD COLUMN IF NOT EXISTS status            text DEFAULT 'active';
ALTER TABLE IF EXISTS public.subscriptions ADD COLUMN IF NOT EXISTS amount            numeric;
ALTER TABLE IF EXISTS public.subscriptions ADD COLUMN IF NOT EXISTS currency          text DEFAULT 'USD';
ALTER TABLE IF EXISTS public.subscriptions ADD COLUMN IF NOT EXISTS subscription_tier text DEFAULT 'free';
ALTER TABLE IF EXISTS public.subscriptions ADD COLUMN IF NOT EXISTS plan              text DEFAULT 'free';
ALTER TABLE IF EXISTS public.subscriptions ADD COLUMN IF NOT EXISTS user_id           uuid;
ALTER TABLE IF EXISTS public.subscriptions ADD COLUMN IF NOT EXISTS family_id         uuid;
ALTER TABLE IF EXISTS public.premium_subscriptions ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';
ALTER TABLE IF EXISTS public.crash_events   ADD COLUMN IF NOT EXISTS response_status text DEFAULT 'detected';
ALTER TABLE IF EXISTS public.emergency_actions ADD COLUMN IF NOT EXISTS status_state text DEFAULT 'active';

-- Multiline index'lerden kacan kolonlar
ALTER TABLE IF EXISTS public.activity_log        ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE IF EXISTS public.activity_log        ADD COLUMN IF NOT EXISTS family_id  uuid;
ALTER TABLE IF EXISTS public.document_reminders  ADD COLUMN IF NOT EXISTS remind_at   timestamptz;
ALTER TABLE IF EXISTS public.document_reminders  ADD COLUMN IF NOT EXISTS sent        boolean DEFAULT false;
ALTER TABLE IF EXISTS public.family_documents    ADD COLUMN IF NOT EXISTS expiry_date timestamptz;
ALTER TABLE IF EXISTS public.location_segments   ADD COLUMN IF NOT EXISTS start_time  timestamptz;
ALTER TABLE IF EXISTS public.location_segments   ADD COLUMN IF NOT EXISTS user_id     uuid;
ALTER TABLE IF EXISTS public.premium_subscriptions ADD COLUMN IF NOT EXISTS user_id   uuid;
ALTER TABLE IF EXISTS public.rotation_rules      ADD COLUMN IF NOT EXISTS family_id   uuid;
ALTER TABLE IF EXISTS public.weather_prefs       ADD COLUMN IF NOT EXISTS user_id     uuid;

SELECT 'PHASE 0 (otomatik) sema uzlastirma tamamlandi' AS result;
