import 'package:flutter/material.dart';

/// Lightweight runtime localization for screens being migrated away from
/// hard-coded strings. ARB remains the long-term source of truth; this layer
/// allows complete TR/NL/FR/EN coverage while the large legacy ARB catalogue
/// is migrated in stages.
class AppStrings {
  const AppStrings._(this._locale);

  final Locale _locale;

  static AppStrings of(BuildContext context) =>
      AppStrings._(Localizations.localeOf(context));

  String get languageCode {
    final code = _locale.languageCode.toLowerCase();
    return _values.containsKey(code) ? code : 'en';
  }

  String text(String key, {Map<String, Object?> args = const {}}) {
    final localeValues = _values[languageCode] ?? _values['en']!;
    var value = localeValues[key] ?? _values['en']![key] ?? key;
    for (final entry in args.entries) {
      value = value.replaceAll('{${entry.key}}', '${entry.value ?? ''}');
    }
    return value;
  }

  static const Map<String, Map<String, String>> _values = {
    'tr': {
      'settings.title': 'Ayarlar',
      'settings.subtitle': "FamilyHub'ınızı yönetin",
      'settings.appearance': 'GÖRÜNÜM',
      'settings.darkTheme': 'Koyu Tema',
      'settings.darkThemeDescription': 'Gece modunda daha rahat kullanım',
      'settings.accentColor': 'Aksan Rengi',
      'settings.accentColorDescription': 'Uygulama vurgu rengini değiştir',
      'settings.fontSize': 'Yazı Boyutu',
      'settings.fontSizeDescription': 'Metin boyutunu ayarla',
      'settings.notifications': 'BİLDİRİMLER',
      'settings.eventReminders': 'Etkinlik Hatırlatmaları',
      'settings.eventRemindersDescription': 'Yaklaşan etkinlikler için bildirimler',
      'settings.taskNotifications': 'Görev Bildirimleri',
      'settings.taskNotificationsDescription': 'Atanan ve yaklaşan görevler',
      'settings.emergencyAlerts': 'Acil Durum Uyarıları',
      'settings.emergencyAlertsDescription': 'Panik butonu ve güvenlik bildirimleri',
      'settings.chatNotifications': 'Sohbet Bildirimleri',
      'settings.chatNotificationsDescription': 'Mesajlar, duyurular ve etiketlemeler',
      'settings.locationNotifications': 'Konum Bildirimleri',
      'settings.locationNotificationsDescription': 'Güvenli bölge giriş ve çıkış uyarıları',
      'settings.family': 'AİLE',
      'settings.familyManagement': 'Aile Yönetimi',
      'settings.familyManagementDescription': 'Üyeleri görüntüle, rolleri düzenle',
      'settings.memberCount': '{count} üye',
      'settings.createInviteCode': 'Davet Kodu Oluştur',
      'settings.createInviteCodeDescription': 'Yeni üyeleri aileye davet et',
      'settings.permissionsRoles': 'İzinler ve Roller',
      'settings.permissionsRolesDescription': 'Her üye için yetki ayarları',
      'settings.childAccounts': 'Çocuk Hesapları',
      'settings.childAccountsDescription': 'PIN ile çocuk girişlerini yönetin',
      'settings.screenTime': 'Ekran Süresi',
      'settings.screenTimeDescription': 'Çocuk üyeler için kullanım limitleri',
      'settings.leaveFamily': 'Aileden Ayrıl',
      'settings.leaveFamilyDescription': 'Bu aileden çıkış yap',
      'settings.account': 'HESAP',
      'settings.profileInformation': 'Profil Bilgileri',
      'settings.profileInformationDescription': 'Ad, fotoğraf ve telefon numarası',
      'settings.security': 'Güvenlik',
      'settings.securityDescription': 'Şifre, iki faktör ve biyometrik giriş',
      'settings.privacy': 'Gizlilik',
      'settings.privacyDescription': 'Veri paylaşımı ve konum izinleri',
      'settings.languageRegion': 'Dil ve Bölge',
      'settings.languageRegionDescription': 'Uygulama dili ve tarih formatı',
      'settings.weather': 'HAVA DURUMU',
      'settings.weatherSettings': 'Hava Durumu Ayarları',
      'settings.weatherSettingsDescription': 'Şehir, birim ve konum tercihleri',
      'settings.dataStorage': 'VERİ VE DEPOLAMA',
      'settings.backup': 'Yedekleme',
      'settings.backupDescription': 'Verilerinizi buluta yedekleyin',
      'settings.restore': 'Geri Yükle',
      'settings.restoreDescription': 'Önceki yedekten veri kurtarın',
      'settings.deleteData': 'Verileri Sil',
      'settings.deleteDataDescription': 'Tüm verilerinizi kalıcı olarak silin',
      'settings.clearCache': 'Önbelleği Temizle',
      'settings.clearCacheDescription': 'Geçici dosyaları temizleyin',
      'settings.premium': 'PREMIUM',
      'settings.free': 'Ücretsiz',
      'settings.basicFeatures': 'Temel özellikler',
      'settings.fourFamilyMembers': '4 aile üyesi',
      'settings.oneGbStorage': '1 GB depolama',
      'settings.unlimitedPhotoStorage': 'Sınırsız fotoğraf depolama',
      'settings.eightFamilyMembers': '8 aile üyesi',
      'settings.aiAssistant': 'AI asistan',
      'settings.advancedSecurity': 'Gelişmiş güvenlik',
      'settings.helpSupport': 'YARDIM VE DESTEK',
      'settings.userGuide': 'Kullanım Kılavuzu',
      'settings.userGuideDescription': "FamilyHub'ı nasıl kullanacağınızı öğrenin",
      'settings.contactSupport': 'Destek ile İletişim',
      'settings.contactSupportDescription': 'Sorularınızı ve önerilerinizi paylaşın',
      'settings.reportBug': 'Hata Bildir',
      'settings.reportBugDescription': 'Karşılaştığınız sorunu raporlayın',
      'settings.rateUs': 'Bizi Değerlendirin',
      'settings.rateUsDescription': "App Store'da puan verin",
      'settings.legal': 'YASAL',
      'settings.privacyPolicy': 'Gizlilik Politikası',
      'settings.privacyPolicyDescription': 'Verilerinizin nasıl korunduğunu öğrenin',
      'settings.terms': 'Kullanım Koşulları',
      'settings.termsDescription': 'Hizmet şartları ve sorumluluklar',
      'settings.about': 'Hakkında',
      'settings.version': 'Sürüm 2.1.0 · FamilyHub Inc.',
      'settings.current': 'Güncel',
      'settings.logout': 'Çıkış Yap',
      'settings.active': 'Aktif',
      'settings.on': 'Açık',
      'settings.highPriority': 'Yüksek Öncelik',
      'settings.secure': 'Güvenli',
      'settings.leaveDialogBody': 'Aileden ayrıldığınızda bu ailedeki erişiminiz kaldırılır. Bu işlem geri alınamaz.',
      'settings.leave': 'Ayrıl',
      'settings.deleteDialogBody': 'Tüm verileriniz kalıcı olarak silinecek. Bu işlem geri alınamaz.',
      'settings.clearCacheDialogBody': 'Geçici dosyalar silinecek. Uygulama ilk açılışta biraz daha yavaş olabilir.',
      'settings.clean': 'Temizle',
      'settings.ratingOpening': 'Değerlendirme sayfası açılıyor',
      'settings.leftFamily': 'Aileden ayrıldınız',
      'settings.leaveError': 'Ayrılma hatası: {error}',
      'settings.allDataDeleted': 'Tüm veriler silindi',
      'settings.deleteError': 'Silme hatası: {error}',
      'settings.cacheCleared': 'Önbellek temizlendi',
      'settings.clearError': 'Temizleme hatası: {error}',
      'settings.noneYet': 'Henüz yok',
      'settings.justNow': 'Az önce',
      'settings.minutesAgo': '{count} dk önce',
      'settings.hoursAgo': '{count} sa önce',
      'settings.daysAgo': '{count} gün önce',
      'appearance.green': 'Yeşil',
      'appearance.orange': 'Turuncu',
      'appearance.purple': 'Mor',
      'appearance.red': 'Kırmızı',
      'appearance.cobalt': 'Kobalt Mavi',
      'appearance.small': 'Küçük',
      'appearance.medium': 'Orta',
      'appearance.large': 'Büyük',
      'appearance.veryLarge': 'Çok Büyük',
      'language.title': 'Dil ve Bölge',
      'language.application': 'UYGULAMA DİLİ',
      'language.region': 'BÖLGE',
      'language.dateFormat': 'TARİH FORMATI',
      'region.be': 'Belçika',
      'region.nl': 'Hollanda',
      'region.fr': 'Fransa',
      'region.tr': 'Türkiye',
      'region.gb': 'Birleşik Krallık',
    },
    'nl': {
      'settings.title': 'Instellingen',
      'settings.subtitle': 'Beheer uw FamilyHub',
      'settings.appearance': 'WEERGAVE',
      'settings.darkTheme': 'Donker thema',
      'settings.darkThemeDescription': 'Comfortabeler gebruik in het donker',
      'settings.accentColor': 'Accentkleur',
      'settings.accentColorDescription': 'Wijzig de accentkleur van de app',
      'settings.fontSize': 'Tekstgrootte',
      'settings.fontSizeDescription': 'Pas de tekstgrootte aan',
      'settings.notifications': 'MELDINGEN',
      'settings.eventReminders': 'Activiteitsherinneringen',
      'settings.eventRemindersDescription': 'Meldingen voor komende activiteiten',
      'settings.taskNotifications': 'Taakmeldingen',
      'settings.taskNotificationsDescription': 'Toegewezen en naderende taken',
      'settings.emergencyAlerts': 'Noodwaarschuwingen',
      'settings.emergencyAlertsDescription': 'Paniekknop- en veiligheidsmeldingen',
      'settings.chatNotifications': 'Chatmeldingen',
      'settings.chatNotificationsDescription': 'Berichten, aankondigingen en vermeldingen',
      'settings.locationNotifications': 'Locatiemeldingen',
      'settings.locationNotificationsDescription': 'Waarschuwingen bij binnenkomst en vertrek uit veilige zones',
      'settings.family': 'GEZIN',
      'settings.familyManagement': 'Gezinsbeheer',
      'settings.familyManagementDescription': 'Bekijk leden en beheer rollen',
      'settings.memberCount': '{count} leden',
      'settings.createInviteCode': 'Uitnodigingscode maken',
      'settings.createInviteCodeDescription': 'Nodig nieuwe leden uit voor het gezin',
      'settings.permissionsRoles': 'Rechten en rollen',
      'settings.permissionsRolesDescription': 'Beheer de rechten van ieder lid',
      'settings.childAccounts': 'Kinderaccounts',
      'settings.childAccountsDescription': 'Beheer kindertoegang met een pincode',
      'settings.screenTime': 'Schermtijd',
      'settings.screenTimeDescription': 'Gebruiksbeperkingen voor kinderen',
      'settings.leaveFamily': 'Gezin verlaten',
      'settings.leaveFamilyDescription': 'Verlaat dit gezin',
      'settings.account': 'ACCOUNT',
      'settings.profileInformation': 'Profielgegevens',
      'settings.profileInformationDescription': 'Naam, foto en telefoonnummer',
      'settings.security': 'Beveiliging',
      'settings.securityDescription': 'Wachtwoord, tweestapsverificatie en biometrie',
      'settings.privacy': 'Privacy',
      'settings.privacyDescription': 'Gegevensdeling en locatierechten',
      'settings.languageRegion': 'Taal en regio',
      'settings.languageRegionDescription': 'App-taal en datumnotatie',
      'settings.weather': 'WEER',
      'settings.weatherSettings': 'Weerinstellingen',
      'settings.weatherSettingsDescription': 'Voorkeuren voor stad, eenheid en locatie',
      'settings.dataStorage': 'GEGEVENS EN OPSLAG',
      'settings.backup': 'Back-up',
      'settings.backupDescription': 'Maak een back-up in de cloud',
      'settings.restore': 'Herstellen',
      'settings.restoreDescription': 'Herstel gegevens uit een eerdere back-up',
      'settings.deleteData': 'Gegevens verwijderen',
      'settings.deleteDataDescription': 'Verwijder al uw gegevens permanent',
      'settings.clearCache': 'Cache wissen',
      'settings.clearCacheDescription': 'Verwijder tijdelijke bestanden',
      'settings.premium': 'PREMIUM',
      'settings.free': 'Gratis',
      'settings.basicFeatures': 'Basisfuncties',
      'settings.fourFamilyMembers': '4 gezinsleden',
      'settings.oneGbStorage': '1 GB opslag',
      'settings.unlimitedPhotoStorage': 'Onbeperkte foto-opslag',
      'settings.eightFamilyMembers': '8 gezinsleden',
      'settings.aiAssistant': 'AI-assistent',
      'settings.advancedSecurity': 'Geavanceerde beveiliging',
      'settings.helpSupport': 'HULP EN ONDERSTEUNING',
      'settings.userGuide': 'Gebruikershandleiding',
      'settings.userGuideDescription': 'Leer hoe u FamilyHub gebruikt',
      'settings.contactSupport': 'Contact opnemen met ondersteuning',
      'settings.contactSupportDescription': 'Deel uw vragen en suggesties',
      'settings.reportBug': 'Probleem melden',
      'settings.reportBugDescription': 'Meld een probleem dat u bent tegengekomen',
      'settings.rateUs': 'Beoordeel ons',
      'settings.rateUsDescription': 'Geef een beoordeling in de App Store',
      'settings.legal': 'JURIDISCH',
      'settings.privacyPolicy': 'Privacybeleid',
      'settings.privacyPolicyDescription': 'Lees hoe uw gegevens worden beschermd',
      'settings.terms': 'Gebruiksvoorwaarden',
      'settings.termsDescription': 'Servicevoorwaarden en verantwoordelijkheden',
      'settings.about': 'Over',
      'settings.version': 'Versie 2.1.0 · FamilyHub Inc.',
      'settings.current': 'Actueel',
      'settings.logout': 'Uitloggen',
      'settings.active': 'Actief',
      'settings.on': 'Aan',
      'settings.highPriority': 'Hoge prioriteit',
      'settings.secure': 'Veilig',
      'settings.leaveDialogBody': 'Wanneer u het gezin verlaat, verliest u de toegang tot de gezinsgegevens. Dit kan niet ongedaan worden gemaakt.',
      'settings.leave': 'Verlaten',
      'settings.deleteDialogBody': 'Al uw gegevens worden permanent verwijderd. Dit kan niet ongedaan worden gemaakt.',
      'settings.clearCacheDialogBody': 'Tijdelijke bestanden worden verwijderd. De app kan bij de eerste start iets trager zijn.',
      'settings.clean': 'Wissen',
      'settings.ratingOpening': 'De beoordelingspagina wordt geopend',
      'settings.leftFamily': 'U hebt het gezin verlaten',
      'settings.leaveError': 'Fout bij verlaten: {error}',
      'settings.allDataDeleted': 'Alle gegevens zijn verwijderd',
      'settings.deleteError': 'Fout bij verwijderen: {error}',
      'settings.cacheCleared': 'Cache gewist',
      'settings.clearError': 'Fout bij wissen: {error}',
      'settings.noneYet': 'Nog niet',
      'settings.justNow': 'Zojuist',
      'settings.minutesAgo': '{count} min geleden',
      'settings.hoursAgo': '{count} uur geleden',
      'settings.daysAgo': '{count} dagen geleden',
      'appearance.green': 'Groen',
      'appearance.orange': 'Oranje',
      'appearance.purple': 'Paars',
      'appearance.red': 'Rood',
      'appearance.cobalt': 'Kobaltblauw',
      'appearance.small': 'Klein',
      'appearance.medium': 'Gemiddeld',
      'appearance.large': 'Groot',
      'appearance.veryLarge': 'Zeer groot',
      'language.title': 'Taal en regio',
      'language.application': 'APP-TAAL',
      'language.region': 'REGIO',
      'language.dateFormat': 'DATUMNOTATIE',
      'region.be': 'België',
      'region.nl': 'Nederland',
      'region.fr': 'Frankrijk',
      'region.tr': 'Turkije',
      'region.gb': 'Verenigd Koninkrijk',
    },
    'fr': {
      'settings.title': 'Paramètres',
      'settings.subtitle': 'Gérez votre FamilyHub',
      'settings.appearance': 'APPARENCE',
      'settings.darkTheme': 'Thème sombre',
      'settings.darkThemeDescription': 'Utilisation plus confortable dans l’obscurité',
      'settings.accentColor': 'Couleur d’accent',
      'settings.accentColorDescription': 'Modifier la couleur d’accent de l’application',
      'settings.fontSize': 'Taille du texte',
      'settings.fontSizeDescription': 'Ajuster la taille du texte',
      'settings.notifications': 'NOTIFICATIONS',
      'settings.eventReminders': 'Rappels d’événements',
      'settings.eventRemindersDescription': 'Notifications pour les événements à venir',
      'settings.taskNotifications': 'Notifications de tâches',
      'settings.taskNotificationsDescription': 'Tâches attribuées et à venir',
      'settings.emergencyAlerts': 'Alertes d’urgence',
      'settings.emergencyAlertsDescription': 'Bouton de panique et notifications de sécurité',
      'settings.chatNotifications': 'Notifications de discussion',
      'settings.chatNotificationsDescription': 'Messages, annonces et mentions',
      'settings.locationNotifications': 'Notifications de localisation',
      'settings.locationNotificationsDescription': 'Alertes d’entrée et de sortie des zones sûres',
      'settings.family': 'FAMILLE',
      'settings.familyManagement': 'Gestion de la famille',
      'settings.familyManagementDescription': 'Afficher les membres et gérer les rôles',
      'settings.memberCount': '{count} membres',
      'settings.createInviteCode': 'Créer un code d’invitation',
      'settings.createInviteCodeDescription': 'Inviter de nouveaux membres dans la famille',
      'settings.permissionsRoles': 'Autorisations et rôles',
      'settings.permissionsRolesDescription': 'Gérer les autorisations de chaque membre',
      'settings.childAccounts': 'Comptes enfants',
      'settings.childAccountsDescription': 'Gérer les accès enfants avec un code PIN',
      'settings.screenTime': 'Temps d’écran',
      'settings.screenTimeDescription': 'Limites d’utilisation pour les enfants',
      'settings.leaveFamily': 'Quitter la famille',
      'settings.leaveFamilyDescription': 'Quitter cette famille',
      'settings.account': 'COMPTE',
      'settings.profileInformation': 'Informations du profil',
      'settings.profileInformationDescription': 'Nom, photo et numéro de téléphone',
      'settings.security': 'Sécurité',
      'settings.securityDescription': 'Mot de passe, double authentification et biométrie',
      'settings.privacy': 'Confidentialité',
      'settings.privacyDescription': 'Partage des données et autorisations de localisation',
      'settings.languageRegion': 'Langue et région',
      'settings.languageRegionDescription': 'Langue de l’application et format de date',
      'settings.weather': 'MÉTÉO',
      'settings.weatherSettings': 'Paramètres météo',
      'settings.weatherSettingsDescription': 'Préférences de ville, d’unité et de localisation',
      'settings.dataStorage': 'DONNÉES ET STOCKAGE',
      'settings.backup': 'Sauvegarde',
      'settings.backupDescription': 'Sauvegarder vos données dans le cloud',
      'settings.restore': 'Restaurer',
      'settings.restoreDescription': 'Récupérer les données d’une sauvegarde précédente',
      'settings.deleteData': 'Supprimer les données',
      'settings.deleteDataDescription': 'Supprimer définitivement toutes vos données',
      'settings.clearCache': 'Vider le cache',
      'settings.clearCacheDescription': 'Supprimer les fichiers temporaires',
      'settings.premium': 'PREMIUM',
      'settings.free': 'Gratuit',
      'settings.basicFeatures': 'Fonctionnalités de base',
      'settings.fourFamilyMembers': '4 membres de la famille',
      'settings.oneGbStorage': '1 Go de stockage',
      'settings.unlimitedPhotoStorage': 'Stockage photo illimité',
      'settings.eightFamilyMembers': '8 membres de la famille',
      'settings.aiAssistant': 'Assistant IA',
      'settings.advancedSecurity': 'Sécurité avancée',
      'settings.helpSupport': 'AIDE ET ASSISTANCE',
      'settings.userGuide': 'Guide d’utilisation',
      'settings.userGuideDescription': 'Apprenez à utiliser FamilyHub',
      'settings.contactSupport': 'Contacter l’assistance',
      'settings.contactSupportDescription': 'Partagez vos questions et suggestions',
      'settings.reportBug': 'Signaler un problème',
      'settings.reportBugDescription': 'Signalez le problème rencontré',
      'settings.rateUs': 'Évaluez-nous',
      'settings.rateUsDescription': 'Donnez une note dans l’App Store',
      'settings.legal': 'JURIDIQUE',
      'settings.privacyPolicy': 'Politique de confidentialité',
      'settings.privacyPolicyDescription': 'Découvrez comment vos données sont protégées',
      'settings.terms': 'Conditions d’utilisation',
      'settings.termsDescription': 'Conditions de service et responsabilités',
      'settings.about': 'À propos',
      'settings.version': 'Version 2.1.0 · FamilyHub Inc.',
      'settings.current': 'À jour',
      'settings.logout': 'Se déconnecter',
      'settings.active': 'Actif',
      'settings.on': 'Activé',
      'settings.highPriority': 'Priorité élevée',
      'settings.secure': 'Sécurisé',
      'settings.leaveDialogBody': 'En quittant la famille, vous perdrez l’accès aux données familiales. Cette action est irréversible.',
      'settings.leave': 'Quitter',
      'settings.deleteDialogBody': 'Toutes vos données seront définitivement supprimées. Cette action est irréversible.',
      'settings.clearCacheDialogBody': 'Les fichiers temporaires seront supprimés. Le premier démarrage pourra être légèrement plus lent.',
      'settings.clean': 'Vider',
      'settings.ratingOpening': 'Ouverture de la page d’évaluation',
      'settings.leftFamily': 'Vous avez quitté la famille',
      'settings.leaveError': 'Erreur lors du départ : {error}',
      'settings.allDataDeleted': 'Toutes les données ont été supprimées',
      'settings.deleteError': 'Erreur de suppression : {error}',
      'settings.cacheCleared': 'Cache vidé',
      'settings.clearError': 'Erreur lors du nettoyage : {error}',
      'settings.noneYet': 'Pas encore',
      'settings.justNow': 'À l’instant',
      'settings.minutesAgo': 'Il y a {count} min',
      'settings.hoursAgo': 'Il y a {count} h',
      'settings.daysAgo': 'Il y a {count} jours',
      'appearance.green': 'Vert',
      'appearance.orange': 'Orange',
      'appearance.purple': 'Violet',
      'appearance.red': 'Rouge',
      'appearance.cobalt': 'Bleu cobalt',
      'appearance.small': 'Petite',
      'appearance.medium': 'Moyenne',
      'appearance.large': 'Grande',
      'appearance.veryLarge': 'Très grande',
      'language.title': 'Langue et région',
      'language.application': 'LANGUE DE L’APPLICATION',
      'language.region': 'RÉGION',
      'language.dateFormat': 'FORMAT DE DATE',
      'region.be': 'Belgique',
      'region.nl': 'Pays-Bas',
      'region.fr': 'France',
      'region.tr': 'Turquie',
      'region.gb': 'Royaume-Uni',
    },
    'en': {
      'settings.title': 'Settings',
      'settings.subtitle': 'Manage your FamilyHub',
      'settings.appearance': 'APPEARANCE',
      'settings.darkTheme': 'Dark theme',
      'settings.darkThemeDescription': 'More comfortable use in low light',
      'settings.accentColor': 'Accent colour',
      'settings.accentColorDescription': 'Change the app accent colour',
      'settings.fontSize': 'Text size',
      'settings.fontSizeDescription': 'Adjust the text size',
      'settings.notifications': 'NOTIFICATIONS',
      'settings.eventReminders': 'Event reminders',
      'settings.eventRemindersDescription': 'Notifications for upcoming events',
      'settings.taskNotifications': 'Task notifications',
      'settings.taskNotificationsDescription': 'Assigned and upcoming tasks',
      'settings.emergencyAlerts': 'Emergency alerts',
      'settings.emergencyAlertsDescription': 'Panic button and safety notifications',
      'settings.chatNotifications': 'Chat notifications',
      'settings.chatNotificationsDescription': 'Messages, announcements and mentions',
      'settings.locationNotifications': 'Location notifications',
      'settings.locationNotificationsDescription': 'Safe-zone entry and exit alerts',
      'settings.family': 'FAMILY',
      'settings.familyManagement': 'Family management',
      'settings.familyManagementDescription': 'View members and manage roles',
      'settings.memberCount': '{count} members',
      'settings.createInviteCode': 'Create invitation code',
      'settings.createInviteCodeDescription': 'Invite new members to the family',
      'settings.permissionsRoles': 'Permissions and roles',
      'settings.permissionsRolesDescription': 'Manage permissions for each member',
      'settings.childAccounts': 'Child accounts',
      'settings.childAccountsDescription': 'Manage child access with a PIN',
      'settings.screenTime': 'Screen time',
      'settings.screenTimeDescription': 'Usage limits for child members',
      'settings.leaveFamily': 'Leave family',
      'settings.leaveFamilyDescription': 'Leave this family',
      'settings.account': 'ACCOUNT',
      'settings.profileInformation': 'Profile information',
      'settings.profileInformationDescription': 'Name, photo and phone number',
      'settings.security': 'Security',
      'settings.securityDescription': 'Password, two-factor authentication and biometrics',
      'settings.privacy': 'Privacy',
      'settings.privacyDescription': 'Data sharing and location permissions',
      'settings.languageRegion': 'Language and region',
      'settings.languageRegionDescription': 'App language and date format',
      'settings.weather': 'WEATHER',
      'settings.weatherSettings': 'Weather settings',
      'settings.weatherSettingsDescription': 'City, unit and location preferences',
      'settings.dataStorage': 'DATA AND STORAGE',
      'settings.backup': 'Backup',
      'settings.backupDescription': 'Back up your data to the cloud',
      'settings.restore': 'Restore',
      'settings.restoreDescription': 'Recover data from a previous backup',
      'settings.deleteData': 'Delete data',
      'settings.deleteDataDescription': 'Permanently delete all your data',
      'settings.clearCache': 'Clear cache',
      'settings.clearCacheDescription': 'Remove temporary files',
      'settings.premium': 'PREMIUM',
      'settings.free': 'Free',
      'settings.basicFeatures': 'Core features',
      'settings.fourFamilyMembers': '4 family members',
      'settings.oneGbStorage': '1 GB storage',
      'settings.unlimitedPhotoStorage': 'Unlimited photo storage',
      'settings.eightFamilyMembers': '8 family members',
      'settings.aiAssistant': 'AI assistant',
      'settings.advancedSecurity': 'Advanced security',
      'settings.helpSupport': 'HELP AND SUPPORT',
      'settings.userGuide': 'User guide',
      'settings.userGuideDescription': 'Learn how to use FamilyHub',
      'settings.contactSupport': 'Contact support',
      'settings.contactSupportDescription': 'Share your questions and suggestions',
      'settings.reportBug': 'Report a problem',
      'settings.reportBugDescription': 'Report an issue you encountered',
      'settings.rateUs': 'Rate us',
      'settings.rateUsDescription': 'Leave a rating in the App Store',
      'settings.legal': 'LEGAL',
      'settings.privacyPolicy': 'Privacy policy',
      'settings.privacyPolicyDescription': 'Learn how your data is protected',
      'settings.terms': 'Terms of use',
      'settings.termsDescription': 'Service terms and responsibilities',
      'settings.about': 'About',
      'settings.version': 'Version 2.1.0 · FamilyHub Inc.',
      'settings.current': 'Up to date',
      'settings.logout': 'Log out',
      'settings.active': 'Active',
      'settings.on': 'On',
      'settings.highPriority': 'High priority',
      'settings.secure': 'Secure',
      'settings.leaveDialogBody': 'When you leave the family, you will lose access to its data. This action cannot be undone.',
      'settings.leave': 'Leave',
      'settings.deleteDialogBody': 'All your data will be permanently deleted. This action cannot be undone.',
      'settings.clearCacheDialogBody': 'Temporary files will be removed. The app may start slightly slower the first time.',
      'settings.clean': 'Clear',
      'settings.ratingOpening': 'Opening the rating page',
      'settings.leftFamily': 'You left the family',
      'settings.leaveError': 'Leave error: {error}',
      'settings.allDataDeleted': 'All data deleted',
      'settings.deleteError': 'Delete error: {error}',
      'settings.cacheCleared': 'Cache cleared',
      'settings.clearError': 'Clear error: {error}',
      'settings.noneYet': 'Not yet',
      'settings.justNow': 'Just now',
      'settings.minutesAgo': '{count} min ago',
      'settings.hoursAgo': '{count} hr ago',
      'settings.daysAgo': '{count} days ago',
      'appearance.green': 'Green',
      'appearance.orange': 'Orange',
      'appearance.purple': 'Purple',
      'appearance.red': 'Red',
      'appearance.cobalt': 'Cobalt blue',
      'appearance.small': 'Small',
      'appearance.medium': 'Medium',
      'appearance.large': 'Large',
      'appearance.veryLarge': 'Very large',
      'language.title': 'Language and region',
      'language.application': 'APP LANGUAGE',
      'language.region': 'REGION',
      'language.dateFormat': 'DATE FORMAT',
      'region.be': 'Belgium',
      'region.nl': 'Netherlands',
      'region.fr': 'France',
      'region.tr': 'Türkiye',
      'region.gb': 'United Kingdom',
    },
  };
}

extension AppStringsBuildContext on BuildContext {
  AppStrings get strings => AppStrings.of(this);
}
